name: Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: ["16", "14", "12"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Rust stable
        shell: bash
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable -y
          source $HOME/.cargo/env
          rustup component add clippy
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack

      - name: Test Rust and build wasm
        env:
          PROJECT_NAME: audit-exclude
          RUST_BACKTRACE: full
        shell: bash
        run: |
          cargo clippy -- -D warnings
          cargo test --verbose
          wasm-pack build --target nodejs
